name: Deploy CalorieMate to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install deps and build
      - run: npm ci
      - run: npm run build
      # Publish to gh-pages branch
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # optional: if you need a custom domain:
